name: quality-metric adocbuild and upload files to server

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - vocabularies/quality-metric/**
  workflow_dispatch:

jobs:
  adoc_build_and_upload_files:
    name: Upload vocabulary to static-rdf-server
    # Prevent a workflow_dispatch from a non-main branch from publishing to data.norge.no.
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      program_html: |
        asciidoctor -a data-uri -o vocabularies/quality-metric/quality-metric-nb.html -a lang=nb vocabularies/quality-metric/main-nb.adoc
        asciidoctor -a data-uri -o vocabularies/quality-metric/quality-metric-en.html -a lang=en vocabularies/quality-metric/main-en.adoc
      host: https://data.norge.no
      ontology: quality-metric
      ontology-type: vocabulary
      files: |
        vocabularies/quality-metric/quality-metric.ttl text/turtle en
        vocabularies/quality-metric/quality-metric-nb.html text/html nb
        vocabularies/quality-metric/quality-metric-en.html text/html en
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
