name: event-type adocbuild and upload files to server

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - vocabularies/event-type/**

jobs:
  adoc_build_and_upload_files:
    runs-on: ubuntu-latest
    name: asciidoctor build
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Build html bokmål
        id: adocbuild-nb
        uses: Analog-inc/asciidoctor-action@master
        with:
          shellcommand: "asciidoctor -a data-uri -o vocabularies/event-type/event-type-nb.html -a lang=nb vocabularies/event-type/main-nb.adoc"
      - name: Build html english
        id: adocbuild-en
        uses: Analog-inc/asciidoctor-action@master
        with:
          shellcommand: "asciidoctor -a data-uri -o vocabularies/event-type/event-type-en.html -a lang=en vocabularies/event-type/main-en.adoc"

      - name: Upload files to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@f9b41f11e07006762215dbd80a6e09b97834f93c
        id: upload-files
        with:
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          ontology-type: "vocabulary"
          ontology: "event-type"
          files: |
            vocabularies/event-type/event-type.ttl text/turtle en
            vocabularies/event-type/event-type-nb.html text/html nb
            vocabularies/event-type/event-type-en.html text/html en
            
