name: business-event-type adocbuild and upload files to server

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - vocabularies/business-event-type/**

jobs:
  adoc_build_and_uploading_of_file:
    runs-on: ubuntu-latest
    name: asciidoctor build and uploading of files
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Build html bokmål
        id: adocbuild-nb
        uses: Analog-inc/asciidoctor-action@master
        with:
          shellcommand: "asciidoctor -a data-uri -o vocabularies/business-event-type/business-event-type-nb.html -a lang=nb vocabularies/business-event-type/main-nb.adoc"
      - name: Build html english
        id: adocbuild-en
        uses: Analog-inc/asciidoctor-action@master
        with:
          shellcommand: "asciidoctor -a data-uri -o vocabularies/business-event-type/business-event-type-en.html -a lang=en vocabularies/business-event-type/main-en.adoc"

      - name: Upload files nb to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@84beeeacd364f310ef6a253bc079354cdf62e5dd
        id: upload-files
        with:
          ontology-type: "vocabulary"
          ontology: "business-event-type"
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            vocabularies/business-event-type/business-event-type.ttl text/turtle en
            vocabularies/business-event-type/business-event-type-nb.html text/html nb
            vocabularies/business-event-type/business-event-type-en.html text/html en

