name: upload files to server

on:
  push:
    branches:
      - main
    paths:
      - vocabularies/level-of-certification/**

jobs:
  test_uploading_of_file:
    name: Upload vocabulary to static-rdf-server
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-files
        with:
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          ontology-type: "vocabulary"
          ontology: "level-of-certification"
          files: |
            vocabularies/level-of-certification/level-of-certification.ttl text/turtle en
            vocabularies/level-of-certification/level-of-certification-nb.html text/html nb
            vocabularies/level-of-certification/level-of-certification-en.html text/html en
            
