name: quality-metric adocbuild and upload files to server

on:
  push:
    branches:
      - main
    paths:
      - vocabularies/quality-metric/**

jobs:
  adoc_build_and_upload_files:
    runs-on: ubuntu-latest
    name: asciidoctor build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build html bokmål
        id: adocbuild-nb
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -a data-uri -o vocabularies/quality-metric/quality-metric-nb.html -a lang=nb vocabularies/quality-metric/main-nb.adoc"
      - name: Build html english
        id: adocbuild-en
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -a data-uri -o vocabularies/quality-metric/quality-metric-en.html -a lang=en vocabularies/quality-metric/main-en.adoc"

      - name: Upload files to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-files
        with:
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          ontology-type: "vocabulary"
          ontology: "quality-metric"
          files: |
            vocabularies/quality-metric/quality-metric.ttl text/turtle en
            vocabularies/quality-metric/quality-metric-nb.html text/html nb
            vocabularies/quality-metric/quality-metric-en.html text/html en
            
