name: service-type adocbuild and upload files to server

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - vocabularies/service-type/**
  workflow_dispatch:

jobs:
  adoc_build_and_upload_files:
    name: Upload vocabulary to static-rdf-server
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      program_html: |
        asciidoctor -a data-uri -o vocabularies/service-type/service-type-nb.html -a lang=nb vocabularies/service-type/main-nb.adoc
        asciidoctor -a data-uri -o vocabularies/service-type/service-type-en.html -a lang=en vocabularies/service-type/main-en.adoc
      host: https://data.norge.no
      ontology: service-type
      ontology-type: vocabulary
      files: |
        vocabularies/service-type/service-type.ttl text/turtle en
        vocabularies/service-type/service-type-nb.html text/html nb
        vocabularies/service-type/service-type-en.html text/html en
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
