name: upload files to server

on:
  push:
    branches:
      - main
    paths:
      - vocabularies/public-service-type/**

jobs:
  test_uploading_of_file:
    name: Upload vocabulary to static-rdf-server
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to static-rdf-server in staging
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v1.0.0-alpha.1
        id: upload-files
        with:
          ontology-type: "vocabulary"
          ontology: "public-service-type"
          rdf-file: "vocabularies/public-service-type/public-service-type.ttl"
          html-file: "vocabularies/public-service-type/index.html;filename=public-service-type.html"
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
