name: level-of-certification adocbuild and upload files to server

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - vocabularies/level-of-certification/**
  workflow_dispatch:

jobs:
  adoc_build_and_upload_files:
    name: Upload vocabulary to static-rdf-server
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      program_html: |
        asciidoctor -a data-uri -o vocabularies/level-of-certification/level-of-certification-nb.html -a lang=nb vocabularies/level-of-certification/main-nb.adoc
        asciidoctor -a data-uri -o vocabularies/level-of-certification/level-of-certification-en.html -a lang=en vocabularies/level-of-certification/main-en.adoc
      host: https://data.norge.no
      ontology: level-of-certification
      ontology-type: vocabulary
      files: |
        vocabularies/level-of-certification/level-of-certification.ttl text/turtle en
        vocabularies/level-of-certification/level-of-certification-nb.html text/html nb
        vocabularies/level-of-certification/level-of-certification-en.html text/html en
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
